parameters:
    airos_core.setup_listener.class: Airos\CoreBundle\EventListener\AirosSetupListener

services:
    airos_core.setup_listener:
        class: %airos_core.setup_listener.class%
        scope: request
        arguments: [@router]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: -10 }
